server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: my_route
          uri: lb:https://user-service
          predicates:
            - Path=/api/user/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
grpc:
  client:
    AuthService:
      address: discovery:///auth-service
      negotiation-type: PLAINTEXT_UPGRADE

