spring:
  datasource:
    url: jdbc:postgresql://${MESSAGE_DB_HOST:localhost}:5433/message_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/
grpc:
  client:
    UserService:
      address: discovery:///user-service
      negotiation-type: PLAINTEXT_UPGRADE
server:
  port: 8084
